services:
  mongo:
    image: mongo:6
    container_name: task-manager-mongo
    environment:
      MONGO_INITDB_DATABASE: taskmanager
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - task-manager-network

  redis:
    image: redis:7-alpine
    container_name: task-manager-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - task-manager-network

  server:
    build: ./server
    container_name: task-manager-server
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo:27017/taskmanager
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - task-manager-network

  client:
    build: ./client
    container_name: task-manager-client
    environment:
      REACT_APP_GRAPHQL_URL: http://localhost:4000/graphql
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - task-manager-network

volumes:
  mongo_data:
  redis_data:

networks:
  task-manager-network:
    driver: bridge